main = ".open-next/worker.js"
name = "ost-opengragph"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[limits]
cpu_ms = 60_000
